apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluebell-deployment
spec:
  selector:
    matchLabels:
      app: bluebell
  template:
    metadata:
      labels:
        app: bluebell
    spec:
      containers:
      - name: bluebell
        image: longpeng1899/bluebell:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9091

---
apiVersion: v1
kind: Service
metadata:
  name: bluebell-service
spec:
  selector:
    app: bluebell
  ports:
  - port: 9091
    targetPort: 9091
